#!/usr/bin/env python

# Modified from https://github.com/ros-teleop/teleop_twist_keyboard
# Original author: Graylin Trevor Jay
# Website: http://wiki.ros.org/teleop_twist_keyboard

import sys
import select
import tty
import termios
from termios import tcflush, TCIFLUSH

import roslib
import rospy

from geometry_msgs.msg import Twist


msg = """
Reading from the keyboard  and Publishing to Twist!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .
For Holonomic mode (strafing), hold down the shift key:
---------------------------
   U    I    O
   J    K    L
   M    <    >
t : up (+z)
b : down (-z)
anything else : stop
ESC to quit
"""

moveBindings = {
        'i':(1,0,0,0),
        'o':(1,0,0,-1),
        'j':(0,0,0,1),
        'l':(0,0,0,-1),
        'u':(1,0,0,1),
        ',':(-1,0,0,0),
        '.':(-1,0,0,1),
        'm':(-1,0,0,-1),
        'O':(1,-1,0,0),
        'I':(1,0,0,0),
        'J':(0,1,0,0),
        'L':(0,-1,0,0),
        'U':(1,1,0,0),
        '<':(-1,0,0,0),
        '>':(-1,-1,0,0),
        'M':(-1,1,0,0),
        't':(0,0,1,0),
        'b':(0,0,-1,0),
    }

key = ""

def isData():
    return select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], [])

if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin)


    rospy.init_node('keyboard_node')

    robot_name = rospy.get_param('/robot_name')
    pub = rospy.Publisher('%s/wb_controller/twist'%(robot_name), Twist, queue_size = 1)

    old_settings = termios.tcgetattr(sys.stdin)

    x = 0
    y = 0
    z = 0
    th = 0

    try:
        tty.setcbreak(sys.stdin.fileno())

        print(msg)

        while 1:

            if isData():
                key = sys.stdin.read(1)

                if key == '\x1b':         # x1b is ESC
                    break
            else:
                key = ""

            if key in moveBindings.keys():
                x = moveBindings[key][0]
                y = moveBindings[key][1]
                z = moveBindings[key][2]
                th = moveBindings[key][3]
            else:
                x = 0
                y = 0
                z = 0
                th = 0

            twist = Twist()
            twist.linear.x = x; twist.linear.y = y; twist.linear.z = z;
            twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = th
            pub.publish(twist)

            termios.tcflush(sys.stdin, TCIFLUSH)

            rospy.sleep(0.1)

    finally:
        x = 0
        y = 0
        z = 0
        th = 0
        twist = Twist()
        twist.linear.x = x; twist.linear.y = y; twist.linear.z = z;
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = th
        pub.publish(twist)
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)
