#!/usr/bin/env python

# WOLF Keyboard controller

import pygame

import rospy
import numpy as np

from geometry_msgs.msg import Twist

import rospkg

rospack = rospkg.RosPack()
rospack.list()
img_path = rospack.get_path('wb_controller') + "/resources/keyboard_controls.png"

msg = """
Reading from the keyboard  and Publishing to Twist!
---------------------------
Moving around:
  q   w   e
  a   s   d

o : up (+z)
l : down (-z)
"""


moveBindings = {
        "w": np.array([1,0,0,0]),
        "s": np.array([-1,0,0,0]),
        "a": np.array([0,0,0,1]),
        "d": np.array([0,0,0,-1]),
        "q": np.array([0, 1, 0, 0]),
        "e": np.array([0, -1, 0, 0]),
        "o": np.array([0,0,1,0]),
        "l": np.array([0,0,-1,0])
    }


if __name__=="__main__":
    rospy.init_node('keyboard_node')

    robot_name = rospy.get_param('/robot_name')
    pub = rospy.Publisher('%s/wb_controller/twist'%(robot_name), Twist, queue_size = 1)

    pygame.init()

    white = (255, 255, 255)
    X = 760
    Y = 340
    display_surface = pygame.display.set_mode((X, Y))

    pygame.display.set_caption('Keyboard controls')

    # create a surface object, image is drawn on it.
    image = pygame.image.load(img_path)

    while not rospy.is_shutdown():
        display_surface.fill(white)
        display_surface.blit(image, (-100, -100))

        pygame.event.pump()
        keys = pygame.key.get_pressed()

        command = np.array([0, 0, 0, 0])
        for key in moveBindings:
            if keys[ord(key)]:
                command += moveBindings[key]

        if keys[pygame.K_LCTRL] and keys[pygame.K_c]:
            exit()

        twist = Twist()
        twist.linear.x = command[0]
        twist.linear.y = command[1]
        twist.linear.z = command[2]
        twist.angular.x = 0.
        twist.angular.y = 0.
        twist.angular.z = command[3]
        pub.publish(twist)

        pygame.display.update()

        rospy.sleep(0.01)




